apiVersion: v1
kind: Service
metadata:
  name: supertokens
  labels:
    app: supertokens
spec:
  selector:
    app: supertokens
  ports:
  - port: {{ .Values.supertokens.service.port }}
    targetPort: {{ .Values.supertokens.containerPort }}
  type: {{ .Values.supertokens.service.type }} 